name: Creates and deploys Documentation

on:
  push:
    branch: [master, feature-doxygen-gh-pages]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build Documentation
      uses: mattnotmitt/doxygen-action@v1.2.3
      with:
        working-directory: 'build/docs'
        doxyfile-path: '../../docs/Doxyfile.in'
    - name: Publishing Documentation
      uses: peaceiris/actions-gh-pages@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: /build/docs
