name: Check Unittests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: creating build
      run: mkdir -p build && cd build
    - name: cmake
      run: cmake ..
    - name: make
      run: make
    - name: run unittests
      run: ./tests/unittests
