name: Check Unittests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Building and running Unittests
      run: |
        sudo apt-get install libgtest-dev
        mkdir -p build
        cd build
        cmake ..
        make
        ./tests/unittests
